language: node_js
node_js:
  - 10.15.3
cache: yarn

install:
 - yarn
 branches:
  only:
  - master
  - gh-pages
script:
   - yarn test
   - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master