export const ADD_REMINDER = 'ADD_REMINDER';
export const EDIT_REMINDER = 'EDIT_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const DELETE_ALL_DATE_REMINDERS = 'DELETE_ALL_DATE_REMINDERS';

export const ADD_CURRENT_DATE = 'ADD_CURRENT_DATE';

export const SET_WEATHER = 'SET_WEATHER';
export const SET_WEATHER_FAIL = 'SET_WEATHER_FAIL';
